# fly.toml app configuration file generated for fly-io-arspzg on 2025-07-17T00:25:22Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'fly-io-arspzg'
primary_region = 'fra'

[build]

# changed this to avoid repeated instances of fly-relay in Tailscale:
[http_service]
  #internal_port = 8080
  internal_port = 5000
  force_https = true
  #auto_stop_machines = 'stop'
  auto_stop_machines = 'off'     # temporarily prevent idle stop/restarts
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
